name: CI

on: ["push"]

jobs:
  build-without-warnings:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.*
    - name: Restore dependencies
      run: dotnet restore src/ConcurrencyAnalyzers.NET.sln
    - name: Build
      run: dotnet build -c Debug src/ConcurrencyAnalyzers.NET.sln --no-restore --no-incremental /warnaserror

  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.*
    - name: Restore dependencies
      run: dotnet restore src/ConcurrencyAnalyzers.NET.sln
    - name: Build
      run: dotnet build -c Debug src/ConcurrencyAnalyzers.NET.sln --no-restore --no-incremental /property:WarningLevel=0
    - name: Test
      run: dotnet test src/ConcurrencyAnalyzers.NET.sln --no-build --verbosity normal --logger GitHubActions